# Generated by Django 2.0.7 on 2018-07-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sns',
            name='path',
            field=models.CharField(blank=True, max_length=1024, verbose_name='ファイルパス'),
        ),
    ]
