# Generated by Django 2.0.7 on 2018-07-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_sns_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sns',
            options={'ordering': ['created'], 'verbose_name': 'SNS', 'verbose_name_plural': 'SNS'},
        ),
        migrations.RemoveField(
            model_name='sns',
            name='path',
        ),
        migrations.AddField(
            model_name='sns',
            name='color',
            field=models.CharField(blank=True, max_length=7, verbose_name='カラー'),
        ),
    ]
