# Generated by Django 2.0.7 on 2018-08-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0003_auto_20180726_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sns',
            name='color',
            field=models.CharField(blank=True, max_length=9, verbose_name='カラー'),
        ),
    ]
